-- =====================================================
-- PROJECTS
-- =====================================================

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description TEXT,
    context_diagram_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================
-- DFDS
-- =====================================================

CREATE TABLE dfds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level_number INTEGER,
    dfd_parent_id BIGINT,
    project_id BIGINT
);

ALTER TABLE dfds
    ADD CONSTRAINT fk_dfds_project_id
        FOREIGN KEY (project_id)
            REFERENCES projects(id)
            ON DELETE CASCADE;

-- =====================================================
-- DFD ELEMENTS
-- =====================================================

CREATE TABLE dfd_elements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    x_value NUMERIC(10,3),
    y_value NUMERIC(10,3),
    width NUMERIC(10,3),
    height NUMERIC(10,3),
    type VARCHAR(50),
    dfd_id BIGINT,
    uuid_identifier VARCHAR(255)
);

ALTER TABLE dfd_elements
    ADD CONSTRAINT fk_dfd_elements_dfd_id
        FOREIGN KEY (dfd_id)
            REFERENCES dfds(id)
            ON DELETE CASCADE;

ALTER TABLE dfd_elements
    ADD CONSTRAINT uq_dfd_elements_uuid
        UNIQUE (uuid_identifier);

-- =====================================================
-- ACTORS
-- =====================================================

CREATE TABLE actors (
    id BIGINT PRIMARY KEY,
    CONSTRAINT fk_actors_id
        FOREIGN KEY (id)
            REFERENCES dfd_elements(id)
            ON DELETE CASCADE
);

-- =====================================================
-- PROCESSES
-- =====================================================

CREATE TABLE processes (
    id BIGINT PRIMARY KEY,
    dfd_child_id BIGINT,
    CONSTRAINT fk_processes_id
       FOREIGN KEY (id)
           REFERENCES dfd_elements(id)
           ON DELETE CASCADE
);

-- =====================================================
-- DATA STORES
-- =====================================================

CREATE TABLE data_stores (
    id BIGINT PRIMARY KEY,
    CONSTRAINT fk_data_stores_id
     FOREIGN KEY (id)
         REFERENCES dfd_elements(id)
         ON DELETE CASCADE
);

-- =====================================================
-- DATA FLOWS
-- =====================================================

CREATE TABLE data_flows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    description VARCHAR(500),
    source_element_id BIGINT,
    target_element_id BIGINT,
    dfd_id BIGINT,
    source_position NUMERIC(10,3),
    target_position NUMERIC(10,3),

    CONSTRAINT fk_data_flows_source_element
        FOREIGN KEY (source_element_id)
        REFERENCES dfd_elements(id),

    CONSTRAINT fk_data_flows_target_element
        FOREIGN KEY (target_element_id)
        REFERENCES dfd_elements(id),

    CONSTRAINT fk_data_flows_dfd
        FOREIGN KEY (dfd_id)
        REFERENCES dfds(id)
        ON DELETE CASCADE
);
